export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE = 'CHANGE_SERVICE';
export const CHANGE_SERVICE_ID = 'CHANGE_SERVICE_ID';
export const CHANGE_FILTER_QUERY = 'CHANGE_FILTER_QUERY';